name: Enhancement
description: Suggest an enhancement for this project
title: '[Enhancement]: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this enhancement suggestion!
  - type: textarea
    id: enhancement-description
    attributes:
      label: What is your enhancement suggestion?
      description: Please provide a detailed description of the enhancement you are suggesting.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: problem-and-solution
    attributes:
      label: What problem does this enhancement solve?
      description: Please describe the problem this enhancement solves and how it would improve the project.
      placeholder: A clear and concise description of what problem this enhancement solves.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the enhancement suggestion here.
