name: Question
description: Ask a question
title: '[Question]: '
labels: ['question']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this question!
  - type: textarea
    id: question
    attributes:
      label: What is your question?
      description: Please provide a detailed description of your question.
      placeholder: A clear and concise description of what your question is.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the question here.
